spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://192.168.56.101:3306/test?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useServerPrepStmts=true
    username: root
    password: 123456
    hikari:
      minimum-idle: 10
      maximum-pool-size: 200
      idle-timeout: 300000
      max-lifetime: 1200000
